In [34]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [35]:
df = pd.read_csv("hotel_bookings.csv")

In [36]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [37]:
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [38]:
df.sample(5)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
96594,City Hotel,0,18,2016,September,36,3,1,1,2,0.0,0,SC,AUS,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,127.0,1,2,Check-Out,2016-09-05
96394,City Hotel,0,121,2016,August,35,26,2,5,3,0.0,0,BB,FRA,Direct,Direct,0,0,0,F,F,0,No Deposit,NaN,NaN,0,Transient,187.0,0,2,Check-Out,2016-09-02
78696,City Hotel,0,3,2016,January,4,18,1,2,1,0.0,0,BB,PRT,Corporate,Corporate,1,0,8,A,A,0,No Deposit,NaN,40.0,0,Transient-Party,66.0,0,0,Check-Out,2016-01-21
12848,Resort Hotel,1,171,2017,July,29,20,1,3,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,5.0,NaN,0,Transient,156.0,0,0,Canceled,2017-01-30
54387,City Hotel,1,30,2016,July,29,14,0,3,2,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,149.4,0,0,Canceled,2016-06-27

In [39]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 119390
Columns: 32

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [41]:

df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [42]:
df.describe(include="object")

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status,reservation_status_date
count,119390,119390,119390,118902,119390,119390,119390,119390,119390,119390,119390,119390
unique,2,12,5,177,8,5,10,12,3,4,3,926
top,City Hotel,August,BB,PRT,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out,2015-10-21
freq,79330,13877,92310,48590,56477,97870,85994,74053,104641,89613,75166,1461

In [43]:
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

company     112593
agent        16340
country        488
children         4
dtype: int64

In [44]:
df["company"] = df["company"].fillna(0)
df["agent"] = df["agent"].fillna(0)
df["country"] = df["country"].fillna("Unknown")
df["children"] = df["children"].fillna(df["children"].median())
df["meal"] = df["meal"].replace("Undefined", "SC")

In [45]:
df["children"] = df["children"].astype(int)

In [46]:
df["arrival_date"] = pd.to_datetime(
    df["arrival_date_year"].astype(str) + "-" +
    df["arrival_date_month"] + "-" +
    df["arrival_date_day_of_month"].astype(str),
    format="%Y-%B-%d"
)

In [47]:
df.isnull().sum().sum()

np.int64(0)

In [48]:
df.duplicated().sum()

np.int64(31994)

In [49]:
print("Shape Before:", df.shape)

df = df.drop_duplicates().reset_index(drop=True)

print("Shape After:", df.shape)

Shape Before: (119390, 33)
Shape After: (87396, 33)

In [50]:
df.dtypes

hotel                                     object
is_canceled                                int64
lead_time                                  int64
arrival_date_year                          int64
arrival_date_month                        object
arrival_date_week_number                   int64
arrival_date_day_of_month                  int64
stays_in_weekend_nights                    int64
stays_in_week_nights                       int64
adults                                     int64
children                                   int64
babies                                     int64
meal                                      object
country                                   object
market_segment                            object
distribution_channel                      object
is_repeated_guest                          int64
previous_cancellations                     int64
previous_bookings_not_canceled             int64
reserved_room_type                        object
assigned_room_type                        object
booking_changes                            int64
deposit_type                              object
agent                                    float64
company                                  float64
days_in_waiting_list                       int64
customer_type                             object
adr                                      float64
required_car_parking_spaces                int64
total_of_special_requests                  int64
reservation_status                        object
reservation_status_date                   object
arrival_date                      datetime64[ns]
dtype: object

In [51]:
cols = [
    "adults",
    "children",
    "babies",
    "adr",
    "lead_time",
    "stays_in_weekend_nights",
    "stays_in_week_nights"
]

df[cols].describe()

,adults,children,babies,adr,lead_time,stays_in_weekend_nights,stays_in_week_nights
count,87396.000000,87396.000000,87396.000000,87396.000000,87396.000000,87396.000000,87396.000000
mean,1.875795,0.138633,0.010824,106.337246,79.891368,1.005263,2.625395
std,0.626500,0.455871,0.113597,55.013953,86.052325,1.031921,2.053584
min,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,72.000000,11.000000,0.000000,1.000000
50%,2.000000,0.000000,0.000000,98.100000,49.000000,1.000000,2.000000
75%,2.000000,0.000000,0.000000,134.000000,125.000000,2.000000,4.000000
max,55.000000,10.000000,10.000000,5400.000000,737.000000,19.000000,50.000000

In [52]:
df[df["adr"] < 0].shape[0]

1

In [53]:
df = df[df["adr"] >= 0]

In [54]:
df[df["adr"] < 0].shape[0]

0

In [55]:
print(df[df["adr"] > 5000])

            hotel  is_canceled  lead_time  arrival_date_year  \
38749  City Hotel            1         35               2016

      arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
38749              March                        13                         25

       stays_in_weekend_nights  stays_in_week_nights  adults  children  \
38749                        0                     1       2         0

       babies meal country market_segment distribution_channel  \
38749       0   BB     PRT  Offline TA/TO                TA/TO

       is_repeated_guest  previous_cancellations  \
38749                  0                       0

       previous_bookings_not_canceled reserved_room_type assigned_room_type  \
38749                               0                  A                  A

       booking_changes deposit_type  agent  company  days_in_waiting_list  \
38749                1   Non Refund   12.0      0.0                     0

      customer_type     adr  required_car_parking_spaces  \
38749     Transient  5400.0                            0

       total_of_special_requests reservation_status reservation_status_date  \
38749                          0           Canceled              2016-02-19

      arrival_date
38749   2016-03-25

In [56]:
df = df[df["adr"] <= 5000]

In [57]:
df["lead_time"].describe(percentiles=[.95, .99])

count    87394.000000
mean        79.890565
std         86.052295
min          0.000000
50%         49.000000
95%        256.000000
99%        347.000000
max        737.000000
Name: lead_time, dtype: float64

In [58]:
zero_guests = df[
    (df["adults"] == 0) &
    (df["children"] == 0) &
    (df["babies"] == 0)
]

zero_guests.shape[0]

166

In [59]:
df = df[(df["adults"] + df["children"] + df["babies"]) > 0]

In [60]:
df.shape

(87228, 33)

In [61]:
for col in df.columns:
    print(col)
    print(df[col].nunique())
    print("-" * 40)

hotel
2
----------------------------------------
is_canceled
2
----------------------------------------
lead_time
479
----------------------------------------
arrival_date_year
3
----------------------------------------
arrival_date_month
12
----------------------------------------
arrival_date_week_number
53
----------------------------------------
arrival_date_day_of_month
31
----------------------------------------
stays_in_weekend_nights
17
----------------------------------------
stays_in_week_nights
33
----------------------------------------
adults
14
----------------------------------------
children
5
----------------------------------------
babies
5
----------------------------------------
meal
4
----------------------------------------
country
178
----------------------------------------
market_segment
8
----------------------------------------
distribution_channel
5
----------------------------------------
is_repeated_guest
2
----------------------------------------
previous_cancellations
15
----------------------------------------
previous_bookings_not_canceled
73
----------------------------------------
reserved_room_type
9
----------------------------------------
assigned_room_type
11
----------------------------------------
booking_changes
19
----------------------------------------
deposit_type
3
----------------------------------------
agent
334
----------------------------------------
company
349
----------------------------------------
days_in_waiting_list
127
----------------------------------------
customer_type
4
----------------------------------------
adr
8864
----------------------------------------
required_car_parking_spaces
5
----------------------------------------
total_of_special_requests
6
----------------------------------------
reservation_status
3
----------------------------------------
reservation_status_date
926
----------------------------------------
arrival_date
793
----------------------------------------

In [62]:
df["reservation_status_date"] = pd.to_datetime(df["reservation_status_date"])

In [63]:
df["reservation_status_date"].dtype

dtype('<M8[ns]')

In [64]:
for col in [
    "is_repeated_guest",
    "previous_cancellations",
    "previous_bookings_not_canceled"
]:
    print(col)
    print(sorted(df[col].unique()))
    print("-" * 40)

is_repeated_guest
[np.int64(0), np.int64(1)]
----------------------------------------
previous_cancellations
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(11), np.int64(13), np.int64(14), np.int64(19), np.int64(21), np.int64(24), np.int64(25), np.int64(26)]
----------------------------------------
previous_bookings_not_canceled
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72)]
----------------------------------------

In [65]:
df.to_csv("hotel_bookings_cleaned.csv", index=False)